fx: add google login middleware
atlp-rwanda/e-comm-team-axel25-bn pull request #120
Opened 2023-03-23 13:57 UTC by musllim

fx: add google login middleware

# Description
This app had no way to logging using google, the client needed this feature which will return the response to client.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-23 14:10 UTC, ISHIMWE-Aime submitted a review, later dismissed
LGTM

2023-03-23 14:17 UTC, ISHIMWE-Aime commented
But try to fix issues about what hound is tell you and circle ci please; 
despite from that you have done a great work.

2023-04-05 16:23 UTC, SergeInGithub reviewed
Please look into the error hound is picking and make the relevant changes.

2023-04-13 09:51 UTC, emilenfc approved these changes
LGTM

2023-04-20 15:25 UTC, shyakadavis approved these changes
LGTM

2023-04-22 19:40 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-04-25 15:27 UTC, mucyoalexaxel requested changes
@SergeInGithub Check suggested changes below.

2023-04-26 09:23 UTC, musllim commented on src/controllers/googleAuth.controller.ts
verifyGoogleToken function will run the validation of credentials (google token sent in the body from Google) based on GOOGLE_CLIENT_ID and throw an error once on failure or return payload containing all credentials of Google user like email, given_name, family_name, picture.

2023-04-26 15:04 UTC, mucyoalexaxel approved these changes
LGTM

2023-04-26 15:05 UTC, merged