ft: add cart feature(view/add/delete)
atlp-rwanda/e-comm-team-axel25-bn pull request #61
Opened 2023-02-28 10:56 UTC by shyakadavis

# Description

🍏 Delivers #184361231-#184361229-#184361230 where: a User/Buyer 👤  should be able to:
- add items to their cart
- view their cart
- clear their cart

Extended checks are against the situations when user:
- inserts an invalid UUID (isValidUUID() utility check)
- tries to add a quantity that exceeds the stock capacity
- tries to add a product that does't exist
- wants to remove an item from the cart
- wants to view their cart total

Fixes # (issue)

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement 
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-28 11:39 UTC, freddykaberuka approved these changes

2023-02-28 16:07 UTC, mucyoalexaxel requested changes
@shyakadavis 
Great work on this PR. have a look at some of the suggested changes and keep me posted.

2023-02-28 16:07 UTC, mucyoalexaxel commented on src/utils/calculateCartTotal.util.ts
> +    }
```suggestion
```
Refactor this logic using `.reduce()` method on arrays. It is more readable.

2023-02-28 16:07 UTC, mucyoalexaxel commented on src/utils/isValidUUID.util.ts
> +// example of where this function is used: src/controllers/Cart.controller.ts 📐 line 20
```suggestion
```

2023-02-28 16:07 UTC, mucyoalexaxel commented on test/cart.spec.ts
> +import request from 'supertest';
fix this error @shyakadavis

2023-03-01 07:37 UTC, mucyoalexaxel requested changes
@shyakadavis 
Try the suggested changes.

2023-03-01 07:37 UTC, mucyoalexaxel commented on .hound.yml
> +  enabled: true
```suggestion
eslint:
  enabled: true
  config_file: .eslintrc.json
```
Try this.

2023-03-01 07:37 UTC, mucyoalexaxel commented on src/utils/isValidUUID.util.ts
> +  const uuid_regex =
```suggestion
  const uuidRegex =
```

2023-03-01 07:37 UTC, mucyoalexaxel commented on tsconfig.json
> +    "module": "ESNext",
```suggestion
    "module": "commonjs",
```

2023-03-01 09:25 UTC, shyakadavis commented on .hound.yml
> +  enabled: true
Let me take a look.

2023-03-02 19:01 UTC, mucyoalexaxel approved these changes

2023-03-02 19:01 UTC, merged