ft:seller delete specific Item in collection
atlp-rwanda/e-comm-team-axel25-bn pull request #78
Opened 2023-03-05 16:19 UTC by emilenfc

# Description

In this feature, a seller sould delete a specific Item/product from collection

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement 
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-05 19:41 UTC, shyakadavis submitted a review, later dismissed
LGTM

2023-03-06 08:20 UTC, SergeInGithub approved these changes
LGTM

2023-03-06 09:28 UTC, freddykaberuka submitted a review, later dismissed

2023-03-06 09:39 UTC, musllim submitted a review, later dismissed
this looks good

2023-03-07 02:43 UTC, mucyoalexaxel requested changes
Check the requested changes as well.

2023-03-07 02:43 UTC, mucyoalexaxel commented on src/controllers/Product.controller.ts
> +      console.log(`Unexpected error in product deleting: `, error);
use appropiate response messages

2023-03-07 02:43 UTC, mucyoalexaxel commented on src/routes/product.routes.ts
> +//delete one product
```suggestion
```

2023-03-07 06:20 UTC, musllim approved these changes
this works well

2023-03-07 06:52 UTC, mucyoalexaxel approved these changes
LGTM

2023-03-07 11:47 UTC, mucyoalexaxel approved these changes
LGTM

2023-03-07 11:51 UTC, ISHIMWE-Aime approved these changes
LGTM

2023-03-07 11:59 UTC, SergeInGithub approved these changes
LGTM

2023-03-07 12:45 UTC, musllim approved these changes
looks good

2023-03-07 16:44 UTC, musllim commented
I think you have to first fix those hound errors

2023-03-07 16:50 UTC, shyakadavis reviewed
I think what you can do is rebase from main, `again`, and see if Hound CI because aware of the version of the Ts linter being used.

2023-03-07 17:20 UTC, mucyoalexaxel requested changes

2023-03-07 17:20 UTC, mucyoalexaxel commented on .hound.yml
> +    - .tsgit
```suggestion
    - .ts
```

2023-03-07 17:57 UTC, emilenfc commented on .hound.yml
> +    - .tsgit
ooo sorry,  and thank

2023-03-07 19:15 UTC, shyakadavis approved these changes
LGTM 🎉

2023-03-07 21:27 UTC, merged