ft:buyer view order status(add/get/delete)
atlp-rwanda/e-comm-team-axel25-bn pull request #81
Opened 2023-03-05 18:25 UTC by emilenfc

# Description

In this feature, buyer can add create order status ofter he create cart, and he can track order status, Admin can change the order status and send update to the buyer profile

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement 
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-05 18:46 UTC, shyakadavis approved these changes
LGTM 🚀

2023-03-05 18:52 UTC, SergeInGithub approved these changes
LGTM

2023-03-05 19:36 UTC, shyakadavis commented on src/database/models/Order.model.ts
> +  "order",
```suggestion
  "Order",
```

2023-03-05 19:36 UTC, shyakadavis commented on src/database/models/Order.model.ts
> +    freezeTableName: false,
```suggestion
    modelName:'Order',
```

2023-03-06 08:38 UTC, shyakadavis submitted a review, later dismissed
LGTM ⚖️

2023-03-06 08:39 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-03-06 09:47 UTC, mucyoalexaxel requested changes
@emilenfc kindly address the requested changes

2023-03-06 09:47 UTC, mucyoalexaxel commented on src/controllers/Order.controller.ts
> +// To create order
```suggestion
```

2023-03-06 09:47 UTC, mucyoalexaxel commented on src/controllers/Order.controller.ts
> +// clear the orders
```suggestion
```

2023-03-06 09:47 UTC, mucyoalexaxel commented on src/controllers/Order.controller.ts
> +// GET request to retrieve order status information
```suggestion
```

2023-03-06 09:47 UTC, mucyoalexaxel commented on src/database/migrations/20230305181417-create-order-tables.js
> +/* eslint-disable no-undef */
```suggestion
```

2023-03-06 09:47 UTC, mucyoalexaxel commented on src/database/models/Order.model.ts
> +        const deliveryDate = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000); // add 5 days  of order in milliseconds
```suggestion
        const deliveryDate = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000);
```

2023-03-06 12:18 UTC, freddykaberuka approved these changes

2023-03-06 12:33 UTC, merged