feat: buyer can add product to wishlist(post,get and delete)
atlp-rwanda/e-comm-team-axel25-bn pull request #82
Opened 2023-03-05 19:00 UTC by emilenfc

# Description
In this feature, a buyer/ user can add a product to him/her wishlist, (add a product/ get a product and also delete a product from wishlist)

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement 
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-05 19:37 UTC, shyakadavis commented on src/database/models/Wishes.model.ts
> +  "wishlist",
```suggestion
  "Wishlist",
```

2023-03-05 19:38 UTC, shyakadavis commented on src/database/models/Wishes.model.ts
> +    freezeTableName: false,
```suggestion
    modelName:'Wishlist',
```

2023-03-05 19:39 UTC, shyakadavis approved these changes
LGTM

2023-03-05 19:40 UTC, SergeInGithub commented on src/controllers/index.ts
> +export * from "./wish.controller";
Try following the convention we were using of Capital letters on certain file naming
```suggestion
export * from "./Wish.controller";
```

2023-03-05 19:42 UTC, SergeInGithub commented on src/interfaces/index.ts
> +export * from "./wish.interface";
Also here
```suggestion
export * from "./Wish.interface";
```

2023-03-05 19:43 UTC, SergeInGithub commented on src/services/index.ts
> +export * from "./wishes.services";
```suggestion
export * from "./Wishes.services";
```

2023-03-06 05:39 UTC, musllim submitted a review, later dismissed
that looks good

2023-03-06 08:23 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-03-06 08:36 UTC, shyakadavis submitted a review, later dismissed
LGTM 🚤 🎆

2023-03-06 09:39 UTC, mucyoalexaxel requested changes
@emilenfc  remove all the unnecessary comments and the eslint comment under your migration file. 
the rest looks good to me

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/database/migrations/20230305183456-create-wishlist-tables.js
> +/* eslint-disable no-undef */
```suggestion
```

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/routes/wishes.routes.ts
> +wishRouter.post("/:productId", isAuth, addWishlistItem); // add to wishlist
```suggestion
wishRouter.post("/:productId", isAuth, addWishlistItem); ```

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/routes/wishes.routes.ts
> +wishRouter.get("/", [isAuth], getWishlist); // vew all wishes
```suggestion
wishRouter.get("/", [isAuth], getWishlist);
```

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/services/Wishes.services.ts
> +  // Check if the product is already in the wishlist
```suggestion
```

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/services/Wishes.services.ts
> +    // Add the product to the wishlist
```suggestion
```

2023-03-06 09:39 UTC, mucyoalexaxel commented on src/services/Wishes.services.ts
> +  // Get all the productIds in the wishlist
```suggestion
```

2023-03-06 20:14 UTC, mucyoalexaxel approved these changes

2023-03-06 20:14 UTC, merged