ft: #184361206 Setup docker for backend application
atlp-rwanda/e-comm-team-axel25-bn pull request #86
Opened 2023-03-06 05:59 UTC by musllim

This changes setup the following services on local development:

1. express server
2. postgress db.

# Description

there is nothing worry on how heroku will run the app. this is only valid when we run locally, heroku will run the application in normal way

Fixes # (issue)

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement 
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-06 21:10 UTC, emilenfc approved these changes
That's nice, LGTM

2023-03-06 21:10 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-03-07 05:07 UTC, shyakadavis approved these changes
LGTM 🔬 🚀

2023-03-07 18:04 UTC, shyakadavis approved these changes
LGTM 🌤️

2023-03-07 18:23 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-03-08 10:29 UTC, shyakadavis submitted a review, later dismissed
LGTM 🚀

2023-03-08 10:37 UTC, emilenfc approved these changes

2023-03-08 13:09 UTC, shyakadavis submitted a review, later dismissed
LGTM 🏙️

2023-03-08 13:30 UTC, SergeInGithub submitted a review, later dismissed
LGTM

2023-03-09 14:56 UTC, mucyoalexaxel requested changes
Great work here @musllim . Kindly address the suggested change and everything should be good

2023-03-09 14:56 UTC, mucyoalexaxel commented on Dockerfile
> +FROM node:19.5.0-alpine
use the LTS version of node or the same version you have in your docker-compose file. @musllim

2023-03-09 14:56 UTC, mucyoalexaxel commented on Dockerfile
> +CMD yarn migrate:dev && yarn seed:dev && yarn dev
```suggestion
CMD yarn migrate:dev && yarn seed:dev && yarn dev

```
always have a new line at the end of your code

2023-03-09 16:38 UTC, mucyoalexaxel requested changes

2023-03-09 16:38 UTC, mucyoalexaxel commented on Dockerfile
> +FROM node
```suggestion
FROM node:14
``````

2023-03-10 09:43 UTC, mucyoalexaxel approved these changes
LGTM

2023-03-10 09:43 UTC, merged